name: Channel Request
description: Suggest a new channel or update an existing one.
title: "[Channel] "
labels: ["channel-request"]
body:
  - type: input
    id: channel_name
    attributes:
      label: Channel Name
      description: The name of the channel
    validations:
      required: true
  - type: input
    id: youtube_url
    attributes:
      label: YouTube URL
      description: The main YouTube channel URL
    validations:
      required: true
  - type: input
    id: fully_forked
    attributes:
      label: Fully Forked?
      description: true or false
    validations:
      required: true
  - type: textarea
    id: socials
    attributes:
      label: Socials (JSON, optional)
      description: |
        Optionally provide social links as JSON. Example:
        { "twitter": "https://twitter.com/example", "instagram": "https://instagram.com/example" }
      placeholder: '{ "twitter": "https://twitter.com/example" }'
    validations:
      required: false
